name: Visual Regression Testing
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16

      - name: Yarn
        run: npm install --global yarn

      - name: Setup pkgs
        run: yarn install --frozen-lockfile

      - name: Take screenshots
        run: yarn storycap

      - name: Test
        run: yarn reg-suit run
